--malzeme ve hizmet kartlarının kdvlerini günceller
--istisnaları içermez

DECLARE @YeniOran int,@EskiOran int
SET @EskiOran=18
SET @YeniOran=20
UPDATE LG_231_ITEMS SET RETURNPRVAT=@YeniOran WHERE RETURNPRVAT=@EskiOran
UPDATE LG_231_ITEMS SET RETURNVAT=@YeniOran WHERE RETURNVAT=@EskiOran
UPDATE LG_231_ITEMS SET SELLPRVAT=@YeniOran WHERE SELLPRVAT=@EskiOran
UPDATE LG_231_ITEMS SET SELLVAT=@YeniOran WHERE SELLVAT=@EskiOran
UPDATE LG_231_ITEMS SET VAT=@YeniOran WHERE VAT=@EskiOran


UPDATE LG_231_SRVCARD SET RETURNVAT=@YeniOran WHERE RETURNVAT=@EskiOran
UPDATE LG_231_SRVCARD SET VAT=@YeniOran WHERE VAT=@EskiOran
