SELECT
TARIH=KSTF.DATE_,
IRSALIYE_NO=KSTF.FICHENO,
FATURA_NO=KSTF.INVNO,
CARIKODU=KCLC.CODE,
CARIUNVAN=KCLC.DEFINITION_,
ISYERI=SANTIYE.NAME,
MLZ_KOD=KITM.CODE,
MLZ_ADI=KITM.NAME,
MIKTAR=COALESCE(
CASE UINFO1
WHEN 0 THEN KSTL.AMOUNT
ELSE KSTL.AMOUNT*UINFO2/UINFO1
END, KSTL.AMOUNT/1000),
BIRIM=KUNT.CODE,
FIYAT=KSTL.PRICE,
TUTAR=KSTL.VATMATRAH,
KDV=KSTL.VATAMNT,
–Stok hareket satırından gelen KDV
TOPLAM=(KSTL.VATMATRAH+KSTL.VATAMNT)
–Stok hareket toplamı
FROM LG_141_01_STFICHE KSTF
LEFT JOIN LG_141_CLCARD KCLC ON KCLC.LOGICALREF=KSTF.CLIENTREF
LEFT JOIN LG_141_01_STLINE KSTL ON KSTL.STFICHEREF=KSTF.LOGICALREF and LINETYPE=0
LEFT JOIN LG_141_SHIPINFO KSHP ON KSHP.LOGICALREF=KSTF.SHIPINFOREF
LEFT JOIN LG_141_ITEMS KITM ON KITM.LOGICALREF=KSTL.STOCKREF AND KSTL.LINETYPE=0
LEFT JOIN LG_141_UNITSETL KUNT ON KUNT.UNITSETREF=KITM.UNITSETREF AND LINENR=1
LEFT JOIN L_CAPIDIV SANTIYE ON KSTF.BRANCH=SANTIYE.NR –Isyeri1,Isyeri2 …
WHERE
SANTIYE.FIRMNR=141