-- Satılan Ürünlerin Fatura Bilgileri ve Satış Fiyatları


SELECT
INVOICE.DATE_ AS [Tarih],
TIGERDB.dbo.LG_INTTOTIME(INVOICE.TIME_) AS [Saat],
INVOICE.FICHENO [Fiş No],
RTRIM(INVOICE.GENEXP1+' '+INVOICE.GENEXP2+' '+INVOICE.GENEXP3+' '+INVOICE.GENEXP4) AS [Açıklama],
STLINE.CODE [Stok Kodu],
STLINE.AMOUNT [Adet],
STLINE.PRICE [Birim Fiyat]
FROM LG_001_03_INVOICE AS INVOICE WITH (NOLOCK)
RIGHT OUTER JOIN LV_001_03_STLINE AS STLINE ON INVOICE.LOGICALREF = STLINE.INVOICEREF
WHERE(INVOICE.TRCODE IN(8))
AND INVOICE.DATE_ >= '2016-01-01 00:00:00.000'
AND INVOICE.DATE_ <= '2016-12-31 23:59:59.999'
AND (STLINE.CODE IN
(
SELECT CODE
FROM dbo.LG_001_ITEMS
WHERE STGRPCODE = 'STOK'
))
ORDER BY INVOICE.DATE_,
INVOICE.SOURCEINDEX,
INVOICE.FICHENO