-- KULLANICILARIN AYLIK KESTİĞİ FATURA SAYISI

SELECT     [User].NAME, MONTH( INV.DATE_) as AY, INV.TRCODE,COUNT(*) FATSAY
FROM         TIGERDB.dbo.L_CAPIUSER AS [User] INNER JOIN
                      LG_001_02_INVOICE AS INV ON [User].NR = INV.CAPIBLOCK_CREATEDBY
WHERE INV.TRCODE IN (8)
GROUP BY [User].NAME, MONTH( INV.DATE_), INV.TRCODE
ORDER by [User].NAME, MONTH( INV.DATE_)